[package]
name = "smartinis_media_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
mime_guess = "2.0.5"
sea-orm = "1.1.10"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.44.2"
tokio-util = "0.7.15"
tower = "0.5.2"
uuid = "1.16.0"
